/**
 * Type guard utilities
 * Runtime type checking for TypeScript types
 */

import { YouTubeVideo, SubtitleData, ProcessedText } from '../types';

/**
 * Check if object is a valid YouTubeVideo
 */
export function isYouTubeVideo(obj: any): obj is YouTubeVideo {
  return (
    obj &&
    typeof obj === 'object' &&
    typeof obj.id === 'string' &&
    typeof obj.url === 'string' &&
    typeof obj.title === 'string' &&
    typeof obj.duration === 'number' &&
    obj.createdAt instanceof Date &&
    Array.isArray(obj.availableSubtitles)
  );
}

/**
 * Check if object is a valid SubtitleData
 */
export function isSubtitleData(obj: any): obj is SubtitleData {
  return (
    obj &&
    typeof obj === 'object' &&
    typeof obj.videoId === 'string' &&
    typeof obj.language === 'string' &&
    obj.format === 'json3' &&
    typeof obj.isAutoGenerated === 'boolean' &&
    typeof obj.filePath === 'string' &&
    obj.downloadedAt instanceof Date &&
    typeof obj.fileSize === 'number' &&
    obj.content &&
    typeof obj.content === 'object' &&
    Array.isArray(obj.content.events)
  );
}

/**
 * Check if object is a valid ProcessedText
 */
export function isProcessedText(obj: any): obj is ProcessedText {
  return (
    obj &&
    typeof obj === 'object' &&
    typeof obj.videoId === 'string' &&
    typeof obj.sourceLanguage === 'string' &&
    typeof obj.content === 'string' &&
    typeof obj.wordCount === 'number' &&
    obj.processedAt instanceof Date &&
    typeof obj.sourceFile === 'string' &&
    typeof obj.outputFile === 'string' &&
    typeof obj.processingDuration === 'number'
  );
}

/**
 * Check if string is a valid YouTube URL
 */
export function isValidYouTubeUrl(url: string): boolean {
  const youtubeRegex = /^(https?:\/\/)?(www\.)?(youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)[a-zA-Z0-9_-]{11}(&.*)?$/;
  return youtubeRegex.test(url);
}

/**
 * Extract YouTube video ID from URL
 */
export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/watch\?.*v=([a-zA-Z0-9_-]{11})/
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  return null;
}

/**
 * Check if language code is valid
 */
export function isValidLanguageCode(code: string): boolean {
  const validCodes = ['zh', 'en', 'ja', 'ko', 'es', 'fr', 'de', 'ru', 'pt', 'it', 'ar', 'hi'];
  return validCodes.includes(code);
}

/**
 * Check if file path has valid extension
 */
export function isValidSubtitleFile(filePath: string): boolean {
  return filePath.endsWith('.json3');
}

/**
 * Check if file size is within limits
 */
export function isValidFileSize(sizeBytes: number, maxSizeBytes: number = 50 * 1024 * 1024): boolean {
  return sizeBytes > 0 && sizeBytes <= maxSizeBytes;
}

/**
 * Check if string is not empty or whitespace
 */
export function isNonEmptyString(value: any): value is string {
  return typeof value === 'string' && value.trim().length > 0;
}

/**
 * Check if value is a valid positive number
 */
export function isPositiveNumber(value: any): value is number {
  return typeof value === 'number' && !isNaN(value) && value > 0;
}

/**
 * Check if value is a valid date
 */
export function isValidDate(value: any): value is Date {
  return value instanceof Date && !isNaN(value.getTime());
}