/**
 * Subtitle Downloader Component
 * Handles subtitle download with language selection
 */

import { useState, useCallback } from 'react';
import { Download, Loader2, CheckCircle, AlertCircle, Globe } from 'lucide-react';
import { apiClient, DownloadRequest, DownloadResult, YouTubeVideo, SubtitleInfo } from '../services/api';

interface SubtitleDownloaderProps {
  video: YouTubeVideo;
  onDownloadComplete: (result: DownloadResult) => void;
  onError: (error: string) => void;
  disabled?: boolean;
}

export function SubtitleDownloader({ video, onDownloadComplete, onError, disabled = false }: SubtitleDownloaderProps) {
  const [selectedLanguage, setSelectedLanguage] = useState<string>('');
  const [includeAutoGenerated, setIncludeAutoGenerated] = useState(true);
  const [isLoading, setIsLoading] = useState(false);
  const [downloadResult, setDownloadResult] = useState<DownloadResult | null>(null);

  // Get all unique languages, prioritizing manual subtitles
  const getAvailableLanguages = useCallback(() => {
    const languages: Array<{ code: string; name: string; isAuto: boolean }> = [];
    const seen = new Set<string>();

    // Add manual subtitles first
    video.availableSubtitles
      .filter(sub => !sub.isAutoGenerated)
      .forEach(sub => {
        if (!seen.has(sub.language)) {
          languages.push({
            code: sub.language,
            name: sub.languageName,
            isAuto: false
          });
          seen.add(sub.language);
        }
      });

    // Add auto-generated subtitles
    video.availableSubtitles
      .filter(sub => sub.isAutoGenerated)
      .forEach(sub => {
        if (!seen.has(sub.language)) {
          languages.push({
            code: sub.language,
            name: sub.languageName,
            isAuto: true
          });
          seen.add(sub.language);
        }
      });

    return languages;
  }, [video.availableSubtitles]);

  const availableLanguages = getAvailableLanguages();

  const handleDownload = useCallback(async () => {
    if (!selectedLanguage) {
      onError('Please select a language');
      return;
    }

    setIsLoading(true);
    setDownloadResult(null);

    const downloadRequest: DownloadRequest = {
      videoUrl: video.url,
      preferredLanguage: selectedLanguage,
      includeAutoGenerated
    };

    try {
      const response = await apiClient.downloadSubtitles(downloadRequest);

      if (response.success && response.data) {
        setDownloadResult(response.data);
        onDownloadComplete(response.data);
      } else {
        throw new Error(response.error?.message || 'Failed to download subtitles');
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'An error occurred';
      onError(errorMessage);
      setDownloadResult(null);
    } finally {
      setIsLoading(false);
    }
  }, [selectedLanguage, includeAutoGenerated, video.url, onDownloadComplete, onError]);

  return (
    <div className="w-full max-w-2xl mx-auto">
      <div className="bg-white rounded-lg border border-gray-200 p-6 space-y-4">
        <div className="flex items-center space-x-2 mb-4">
          <Download className="h-5 w-5 text-blue-600" />
          <h2 className="text-lg font-semibold text-gray-900">Download Subtitles</h2>
        </div>

        {/* Video info */}
        <div className="bg-gray-50 rounded-lg p-3">
          <p className="text-sm font-medium text-gray-700 truncate">{video.title}</p>
          <p className="text-xs text-gray-500">Duration: {Math.floor(video.duration / 60)}:{(video.duration % 60).toString().padStart(2, '0')}</p>
        </div>

        {/* Language selection */}
        <div>
          <label htmlFor="language" className="block text-sm font-medium text-gray-700 mb-2">
            Select Language
          </label>
          <div className="relative">
            <select
              id="language"
              value={selectedLanguage}
              onChange={(e) => setSelectedLanguage(e.target.value)}
              disabled={disabled || isLoading}
              className="w-full px-4 py-2 pr-10 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent appearance-none disabled:bg-gray-100 disabled:cursor-not-allowed"
            >
              <option value="">Choose a language...</option>
              {availableLanguages.map((lang) => (
                <option key={lang.code} value={lang.code}>
                  {lang.name} {lang.isAuto && '(Auto-generated)'}
                </option>
              ))}
            </select>
            <div className="absolute right-3 top-1/2 transform -translate-y-1/2 pointer-events-none">
              <Globe className="h-4 w-4 text-gray-400" />
            </div>
          </div>
        </div>

        {/* Auto-generated subtitle option */}
        <div className="flex items-center">
          <input
            type="checkbox"
            id="includeAuto"
            checked={includeAutoGenerated}
            onChange={(e) => setIncludeAutoGenerated(e.target.checked)}
            disabled={disabled || isLoading}
            className="h-4 w-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500 disabled:cursor-not-allowed"
          />
          <label htmlFor="includeAuto" className="ml-2 text-sm text-gray-700">
            Include auto-generated subtitles if manual ones aren't available
          </label>
        </div>

        {/* Download result */}
        {downloadResult && (
          <div className="bg-green-50 border border-green-200 rounded-lg p-4">
            <div className="flex items-start space-x-2">
              <CheckCircle className="h-5 w-5 text-green-600 mt-0.5" />
              <div className="flex-1">
                <h3 className="font-medium text-green-900">Download Complete!</h3>
                <div className="mt-2 text-sm text-green-800 space-y-1">
                  <p>Subtitles downloaded: {downloadResult.subtitles.length}</p>
                  <p>Download time: {(downloadResult.downloadDuration / 1000).toFixed(2)}s</p>
                  {downloadResult.subtitles.length > 0 && (
                    <p>Languages: {downloadResult.subtitles.map(s => s.language).join(', ')}</p>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Download button */}
        <button
          onClick={handleDownload}
          disabled={disabled || isLoading || !selectedLanguage}
          className="w-full bg-blue-600 text-white py-3 px-4 rounded-lg font-medium hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors flex items-center justify-center space-x-2"
        >
          {isLoading ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              <span>Downloading...</span>
            </>
          ) : (
            <>
              <Download className="h-4 w-4" />
              <span>Download Subtitles</span>
            </>
          )}
        </button>

        {/* Help text */}
        <div className="text-sm text-gray-600">
          <p>• Manual subtitles provide better quality than auto-generated ones</p>
          <p>• Downloaded subtitles will be stored locally for processing</p>
          <p>• You can process multiple subtitles from the same video</p>
        </div>
      </div>
    </div>
  );
}