/**
 * Subtitle Controller
 * Handles subtitle download and processing
 */

import { Request, Response } from 'express';
import { logger } from '../utils/logger';
import { SubtitleService } from '../services/subtitle.service';
import { ApiResponse } from '../../shared/types/api.types';
import { DownloadRequest, ProcessingRequest } from '../../shared/types/video.types';

export class SubtitleController {
  private subtitleService: SubtitleService;

  constructor() {
    this.subtitleService = new SubtitleService();
  }

  /**
   * Download subtitles for a YouTube video
   * POST /api/subtitles/download
   */
  async downloadSubtitles(req: Request, res: Response): Promise<void> {
    const downloadRequest: DownloadRequest = req.body;

    try {
      logger.info('Starting subtitle download', {
        videoUrl: downloadRequest.videoUrl,
        preferredLanguage: downloadRequest.preferredLanguage,
        includeAutoGenerated: downloadRequest.includeAutoGenerated
      });

      const downloadResult = await this.subtitleService.downloadSubtitles(downloadRequest);

      const response: ApiResponse<typeof downloadResult> = {
        success: true,
        data: downloadResult
      };

      logger.info('Subtitle download completed successfully', {
        videoId: downloadResult.video.id,
        subtitlesCount: downloadResult.subtitles.length,
        duration: downloadResult.downloadDuration
      });

      res.status(200).json(response);
    } catch (error) {
      logger.error('Failed to download subtitles', error);

      const response: ApiResponse<null> = {
        success: false,
        error: {
          code: 'SUBTITLE_DOWNLOAD_ERROR',
          category: 'EXTERNAL_TOOL_ERROR',
          severity: 'HIGH',
          message: error instanceof Error ? error.message : 'Unknown error occurred',
          timestamp: new Date()
        }
      };

      res.status(500).json(response);
    }
  }

  /**
   * Process downloaded subtitles into clean text
   * POST /api/subtitles/process
   */
  async processSubtitles(req: Request, res: Response): Promise<void> {
    const processingRequest: ProcessingRequest = req.body;

    try {
      logger.info('Starting subtitle processing', {
        subtitleFile: processingRequest.subtitleFile,
        outputPath: processingRequest.outputPath
      });

      const processedText = await this.subtitleService.processSubtitles(processingRequest);

      const response: ApiResponse<typeof processedText> = {
        success: true,
        data: processedText
      };

      logger.info('Subtitle processing completed successfully', {
        videoId: processedText.videoId,
        wordCount: processedText.wordCount,
        processingDuration: processedText.processingDuration
      });

      res.status(200).json(response);
    } catch (error) {
      logger.error('Failed to process subtitles', error);

      const response: ApiResponse<null> = {
        success: false,
        error: {
          code: 'SUBTITLE_PROCESSING_ERROR',
          category: 'PROCESSING_ERROR',
          severity: 'HIGH',
          message: error instanceof Error ? error.message : 'Unknown error occurred',
          timestamp: new Date()
        }
      };

      res.status(500).json(response);
    }
  }
}