/**
 * API Client
 * Handles communication with the backend API
 */

// Types for API requests and responses
export interface YouTubeVideo {
  id: string;
  url: string;
  title: string;
  description?: string;
  duration: number;
  uploader?: string;
  uploadDate?: string;
  thumbnailUrl?: string;
  language?: string;
  availableSubtitles: SubtitleInfo[];
  createdAt: string;
}

export interface SubtitleInfo {
  language: string;
  languageName: string;
  isAutoGenerated: boolean;
  format: 'json3';
  url?: string;
}

export interface DownloadRequest {
  videoUrl: string;
  preferredLanguage?: string;
  includeAutoGenerated?: boolean;
}

export interface DownloadResult {
  success: boolean;
  video: YouTubeVideo;
  subtitles: SubtitleData[];
  errors?: string[];
  downloadDuration: number;
}

export interface SubtitleData {
  videoId: string;
  language: string;
  format: 'json3';
  isAutoGenerated: boolean;
  content: any;
  filePath: string;
  downloadedAt: string;
  fileSize: number;
}

export interface ProcessingRequest {
  subtitleFile: string;
  outputPath?: string;
  removeTimestamps: boolean;
  mergeDuplicates: boolean;
  formatParagraphs: boolean;
}

export interface ProcessedText {
  videoId: string;
  sourceLanguage: string;
  content: string;
  wordCount: number;
  processedAt: string;
  sourceFile: string;
  outputFile: string;
  processingDuration: number;
}

export interface SystemStatus {
  ytDlpVersion: string;
  pythonVersion: string;
  pythonScriptVersion?: string;
  nodeVersion: string;
  storagePath: string;
  totalFiles: number;
  totalSize: number;
  uptime: number;
}

export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    category: string;
    severity: string;
    message: string;
    timestamp: string;
  };
}

class ApiClient {
  private baseUrl: string;

  constructor() {
    this.baseUrl = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000';
  }

  private async request<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<ApiResponse<T>> {
    const url = `${this.baseUrl}${endpoint}`;
    const config = {
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
      ...options,
    };

    try {
      const response = await fetch(url, config);
      const data = await response.json();

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${data.error?.message || 'Request failed'}`);
      }

      return data as ApiResponse<T>;
    } catch (error) {
      console.error(`API request failed: ${endpoint}`, error);
      throw error;
    }
  }

  // Video information
  async getVideoInfo(url: string): Promise<ApiResponse<YouTubeVideo>> {
    const params = new URLSearchParams({ url });
    return this.request<YouTubeVideo>(`/api/video/info?${params}`);
  }

  // Subtitle operations
  async downloadSubtitles(request: DownloadRequest): Promise<ApiResponse<DownloadResult>> {
    return this.request<DownloadResult>('/api/subtitles/download', {
      method: 'POST',
      body: JSON.stringify(request),
    });
  }

  async processSubtitles(request: ProcessingRequest): Promise<ApiResponse<ProcessedText>> {
    return this.request<ProcessedText>('/api/subtitles/process', {
      method: 'POST',
      body: JSON.stringify(request),
    });
  }

  // File operations
  async previewFile(fileId: string): Promise<ApiResponse<{
    content: string;
    filename: string;
    size: number;
    createdAt: string;
  }>> {
    return this.request(`/api/files/preview/${fileId}`);
  }

  async downloadFile(fileId: string): Promise<Blob> {
    const url = `${this.baseUrl}/api/files/download/${fileId}`;
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`Download failed: ${response.statusText}`);
    }

    return response.blob();
  }

  // System operations
  async getSystemStatus(): Promise<ApiResponse<SystemStatus>> {
    return this.request<SystemStatus>('/api/system/status');
  }

  async getHealthCheck(): Promise<ApiResponse<{
    healthy: boolean;
    checks: Array<{
      name: string;
      passed: boolean;
      message?: string;
      duration: number;
    }>;
    duration: number;
  }>> {
    return this.request('/api/system/health');
  }

  // Health check (simplified)
  async healthCheck(): Promise<boolean> {
    try {
      const response = await this.request<{ status: string }>('/health');
      return response.success && response.data?.status === 'healthy';
    } catch (error) {
      return false;
    }
  }
}

// Create singleton instance
export const apiClient = new ApiClient();

// Export types for use in components
export type {
  YouTubeVideo,
  SubtitleInfo,
  DownloadRequest,
  DownloadResult,
  SubtitleData,
  ProcessingRequest,
  ProcessedText,
  SystemStatus,
  ApiResponse
};