/**
 * Application configuration
 * Centralized configuration management
 */

import { config as dotenvConfig } from 'dotenv';
import { AppConfig } from '@shared/types';
import { AppError, ErrorCategory, ErrorSeverity } from '@shared/types';

// Load environment variables
dotenvConfig();

/**
 * Validate required environment variables
 */
function validateEnvironment(): void {
  const required = ['NODE_ENV', 'PORT'];
  const missing = required.filter(key => !process.env[key]);

  if (missing.length > 0) {
    throw new AppError(
      'CONFIGURATION_ERROR',
      `Missing required environment variables: ${missing.join(', ')}`,
      ErrorCategory.CONFIGURATION_ERROR,
      ErrorSeverity.CRITICAL
    );
  }
}

/**
 * Get environment variable with fallback
 */
function getEnvVar(key: string, fallback?: string): string {
  const value = process.env[key];
  if (value === undefined) {
    if (fallback !== undefined) {
      return fallback;
    }
    throw new AppError(
      'CONFIGURATION_ERROR',
      `Environment variable ${key} is required but not set`,
      ErrorCategory.CONFIGURATION_ERROR,
      ErrorSeverity.CRITICAL
    );
  }
  return value;
}

/**
 * Get numeric environment variable with fallback
 */
function getEnvNumber(key: string, fallback?: number): number {
  const value = process.env[key];
  if (value === undefined) {
    if (fallback !== undefined) {
      return fallback;
    }
    throw new AppError(
      'CONFIGURATION_ERROR',
      `Environment variable ${key} is required but not set`,
      ErrorCategory.CONFIGURATION_ERROR,
      ErrorSeverity.CRITICAL
    );
  }

  const parsed = parseInt(value, 10);
  if (isNaN(parsed)) {
    throw new AppError(
      'CONFIGURATION_ERROR',
      `Environment variable ${key} must be a valid number, got: ${value}`,
      ErrorCategory.CONFIGURATION_ERROR,
      ErrorSeverity.CRITICAL
    );
  }

  return parsed;
}

/**
 * Get boolean environment variable with fallback
 */
function getEnvBoolean(key: string, fallback?: boolean): boolean {
  const value = process.env[key];
  if (value === undefined) {
    if (fallback !== undefined) {
      return fallback;
    }
    throw new AppError(
      'CONFIGURATION_ERROR',
      `Environment variable ${key} is required but not set`,
      ErrorCategory.CONFIGURATION_ERROR,
      ErrorSeverity.CRITICAL
    );
  }

  return value.toLowerCase() === 'true';
}

// Validate environment
validateEnvironment();

/**
 * Application configuration
 */
export const config: AppConfig = {
  // Basic app configuration
  appName: 'YouTube to Pure Text Generator',
  appVersion: '1.0.0',
  environment: getEnvVar('NODE_ENV', 'development') as 'development' | 'production' | 'test',

  // yt-dlp configuration
  ytdlp: {
    executablePath: getEnvVar('YT_DLP_PATH', 'yt-dlp'),
    timeout: getEnvNumber('YT_DLP_TIMEOUT', 300), // 5 minutes
    retryCount: getEnvNumber('YT_DLP_RETRY_COUNT', 3),
    outputTemplate: getEnvVar('YT_DLP_OUTPUT_TEMPLATE', '%(id)s/%(title)s.%(ext)s'),
    preferredLanguages: getEnvVar('YT_DLP_LANGUAGES', 'en,zh').split(','),
    includeAutoGenerated: getEnvBoolean('YT_DLP_INCLUDE_AUTO', true)
  },

  // Storage configuration
  storage: {
    basePath: getEnvVar('STORAGE_BASE_PATH', './storage'),
    downloadsDir: getEnvVar('STORAGE_DOWNLOADS_DIR', 'downloads'),
    processedDir: getEnvVar('STORAGE_PROCESSED_DIR', 'processed'),
    tempDir: getEnvVar('STORAGE_TEMP_DIR', 'temp'),
    logsDir: getEnvVar('STORAGE_LOGS_DIR', 'logs'),
    maxStorageSize: getEnvNumber('STORAGE_MAX_SIZE', 1024 * 1024 * 1024), // 1GB
    maxFileCount: getEnvNumber('STORAGE_MAX_FILES', 10000),
    autoCleanup: getEnvBoolean('STORAGE_AUTO_CLEANUP', true),
    cleanupInterval: getEnvNumber('STORAGE_CLEANUP_INTERVAL', 24) // 24 hours
  },

  // API configuration
  api: {
    port: getEnvNumber('PORT', 3000),
    host: getEnvVar('HOST', 'localhost'),
    corsEnabled: getEnvBoolean('CORS_ENABLED', true),
    corsOrigins: getEnvVar('CORS_ORIGINS', 'http://localhost:3000,http://localhost:5173').split(','),
    bodyLimit: getEnvVar('API_BODY_LIMIT', '10mb'),
    requestTimeout: getEnvNumber('API_REQUEST_TIMEOUT', 30000), // 30 seconds
    rateLimitEnabled: getEnvBoolean('RATE_LIMIT_ENABLED', true),
    rateLimitWindow: getEnvNumber('RATE_LIMIT_WINDOW', 15), // 15 minutes
    rateLimitMax: getEnvNumber('RATE_LIMIT_MAX', 100)
  },

  // Processing configuration
  processing: {
    pythonPath: getEnvVar('PYTHON_PATH', 'python3'),
    cleaningScriptPath: getEnvVar('CLEANING_SCRIPT_PATH', './scripts/clean_subtitle.py'),
    processingTimeout: getEnvNumber('PROCESSING_TIMEOUT', 120000), // 2 minutes (120 seconds in milliseconds)
    maxFileSize: getEnvNumber('PROCESSING_MAX_FILE_SIZE', 50 * 1024 * 1024), // 50MB
    defaultOptions: {
      removeTimestamps: getEnvBoolean('PROCESSING_REMOVE_TIMESTAMPS', true),
      mergeDuplicates: getEnvBoolean('PROCESSING_MERGE_DUPLICATES', true),
      formatParagraphs: getEnvBoolean('PROCESSING_FORMAT_PARAGRAPHS', true),
      minSegmentLength: getEnvNumber('PROCESSING_MIN_SEGMENT_LENGTH', 10)
    }
  },

  // Logging configuration
  logging: {
    level: getEnvVar('LOG_LEVEL', 'info') as 'debug' | 'info' | 'warn' | 'error',
    logToFile: getEnvBoolean('LOG_TO_FILE', true),
    logFilePath: getEnvVar('LOG_FILE_PATH', './logs/app.log'),
    maxFileSize: getEnvNumber('LOG_MAX_FILE_SIZE', 10 * 1024 * 1024), // 10MB
    maxFiles: getEnvNumber('LOG_MAX_FILES', 5),
    format: getEnvVar('LOG_FORMAT', 'combined'),
    logToConsole: getEnvBoolean('LOG_TO_CONSOLE', true)
  }
};

// Export configuration for use in other modules
export default config;