/**
 * Configuration related type definitions
 * Based on P01-Spec.md configuration parameters
 */

/**
 * yt-dlp configuration
 */
export interface YtdlpConfig {
  /** yt-dlp executable path */
  executablePath: string;
  /** Timeout in seconds */
  timeout: number;
  /** Retry count */
  retryCount: number;
  /** Output template */
  outputTemplate: string;
  /** Preferred languages list */
  preferredLanguages: string[];
  /** Whether to include auto-generated subtitles */
  includeAutoGenerated: boolean;
}

/**
 * Storage configuration
 */
export interface StorageConfig {
  /** Base storage path */
  basePath: string;
  /** Downloads directory */
  downloadsDir: string;
  /** Processed directory */
  processedDir: string;
  /** Temp directory */
  tempDir: string;
  /** Logs directory */
  logsDir: string;
  /** Maximum storage size in bytes */
  maxStorageSize: number;
  /** Maximum file count */
  maxFileCount: number;
  /** Auto cleanup enabled */
  autoCleanup: boolean;
  /** Cleanup interval in hours */
  cleanupInterval: number;
}

/**
 * API server configuration
 */
export interface ApiConfig {
  /** Server port */
  port: number;
  /** Server host */
  host: string;
  /** CORS enabled */
  corsEnabled: boolean;
  /** CORS origins */
  corsOrigins: string[];
  /** Request body size limit */
  bodyLimit: string;
  /** Request timeout in milliseconds */
  requestTimeout: number;
  /** Rate limiting enabled */
  rateLimitEnabled: boolean;
  /** Rate limit window in minutes */
  rateLimitWindow: number;
  /** Rate limit max requests */
  rateLimitMax: number;
}

/**
 * Processing configuration
 */
export interface ProcessingConfig {
  /** Python executable path */
  pythonPath: string;
  /** Cleaning script path */
  cleaningScriptPath: string;
  /** Processing timeout in seconds */
  processingTimeout: number;
  /** Maximum file size in bytes */
  maxFileSize: number;
  /** Default processing options */
  defaultOptions: {
    removeTimestamps: boolean;
    mergeDuplicates: boolean;
    formatParagraphs: boolean;
    minSegmentLength: number;
  };
}

/**
 * Logging configuration
 */
export interface LoggingConfig {
  /** Log level */
  level: 'debug' | 'info' | 'warn' | 'error';
  /** Log to file */
  logToFile: boolean;
  /** Log file path */
  logFilePath: string;
  /** Log file max size in bytes */
  maxFileSize: number;
  /** Log file max count */
  maxFiles: number;
  /** Log format */
  format: string;
  /** Log to console */
  logToConsole: boolean;
}

/**
 * Application configuration
 */
export interface AppConfig {
  /** Application name */
  appName: string;
  /** Application version */
  appVersion: string;
  /** Environment */
  environment: 'development' | 'production' | 'test';
  /** yt-dlp configuration */
  ytdlp: YtdlpConfig;
  /** Storage configuration */
  storage: StorageConfig;
  /** API configuration */
  api: ApiConfig;
  /** Processing configuration */
  processing: ProcessingConfig;
  /** Logging configuration */
  logging: LoggingConfig;
}

/**
 * Configuration validation result
 */
export interface ConfigValidationResult {
  /** Whether valid */
  isValid: boolean;
  /** Error messages */
  errors: string[];
  /** Warning messages */
  warnings: string[];
}