/**
 * Video related type definitions
 * Based on P01-Spec.md data structures
 */

/**
 * YouTube video metadata
 */
export interface YouTubeVideo {
  /** YouTube video ID */
  id: string;
  /** Original URL */
  url: string;
  /** Video title */
  title: string;
  /** Video description (optional) */
  description?: string;
  /** Duration in seconds */
  duration: number;
  /** Uploader name (optional) */
  uploader?: string;
  /** Upload date (optional) */
  uploadDate?: Date;
  /** Thumbnail URL (optional) */
  thumbnailUrl?: string;
  /** Primary language (optional) */
  language?: string;
  /** Available subtitles list */
  availableSubtitles: SubtitleInfo[];
  /** Record creation time */
  createdAt: Date;
}

/**
 * Subtitle information
 */
export interface SubtitleInfo {
  /** Language code (zh, en, etc.) */
  language: string;
  /** Language name (Chinese, English) */
  languageName: string;
  /** Whether auto-generated */
  isAutoGenerated: boolean;
  /** Format type */
  format: 'json3';
  /** Subtitle download URL (optional) */
  url?: string;
}

/**
 * Subtitle data with content
 */
export interface SubtitleData {
  /** Associated video ID */
  videoId: string;
  /** Language code */
  language: string;
  /** Format type */
  format: 'json3';
  /** Whether auto-generated */
  isAutoGenerated: boolean;
  /** JSON3 format content */
  content: JSON3Content;
  /** Local storage path */
  filePath: string;
  /** Download time */
  downloadedAt: Date;
  /** File size in bytes */
  fileSize: number;
}

/**
 * JSON3 subtitle content structure
 */
export interface JSON3Content {
  /** Subtitle events array */
  events: SubtitleEvent[];
}

/**
 * Individual subtitle event
 */
export interface SubtitleEvent {
  /** Start time in milliseconds */
  tStartMs: number;
  /** Duration in milliseconds */
  dDurationMs: number;
  /** Append identifier */
  aAppend: number;
  /** Subtitle segments */
  segs: SubtitleSegment[];
}

/**
 * Subtitle segment
 */
export interface SubtitleSegment {
  /** UTF-8 text content */
  utf8: string;
  /** Segment start time (optional) */
  tStartMs?: number;
  /** Segment end time (optional) */
  tEndMs?: number;
}

/**
 * Processed text data
 */
export interface ProcessedText {
  /** Associated video ID */
  videoId: string;
  /** Source language */
  sourceLanguage: string;
  /** Pure text content */
  content: string;
  /** Word count */
  wordCount: number;
  /** Processing time */
  processedAt: Date;
  /** Source file path */
  sourceFile: string;
  /** Output file path */
  outputFile: string;
  /** Processing duration in milliseconds */
  processingDuration: number;
}

/**
 * Download request for subtitles
 */
export interface DownloadRequest {
  /** YouTube video URL */
  videoUrl: string;
  /** Preferred language (optional) */
  preferredLanguage?: string;
  /** Whether to include auto-generated subtitles */
  includeAutoGenerated?: boolean;
}

/**
 * Download result
 */
export interface DownloadResult {
  /** Whether download was successful */
  success: boolean;
  /** Video information */
  video: YouTubeVideo;
  /** Downloaded subtitle data */
  subtitles: SubtitleData[];
  /** Error information (if any) */
  errors?: string[];
  /** Download duration in milliseconds */
  downloadDuration: number;
}

/**
 * Processing request for subtitles
 */
export interface ProcessingRequest {
  /** Subtitle file path */
  subtitleFile: string;
  /** Output path (optional) */
  outputPath?: string;
  /** Whether to remove timestamps */
  removeTimestamps: boolean;
  /** Whether to merge duplicates */
  mergeDuplicates: boolean;
  /** Whether to format paragraphs */
  formatParagraphs: boolean;
}